"""SSOT generation-config builder — one template, per-domain overrides.

Replaces the configs/gen<N>_leaf_<d>.yaml proliferation (185 files):
every generation's configs are DERIVED here and written into that
generation's own checkpoint directory
(``checkpoints/gen<N>/configs/``), never into ``configs/``.

Design (KISS / DRY):
- ``LEAF_TEMPLATE`` — the single leaf YAML (geometry, optimizer,
  guards). Only the values that genuinely differ per domain live in
  ``DOMAINS``.
- ``DOMAINS`` — per-domain overrides: data mix, head regularization,
  step budget, data-seed offsets. These are the measured winning-line
  values (gen-18..gen-40 lineage); change them HERE, nowhere else.
- ``write_generation(gen, root_ckpt, seed_base)`` — materializes
  ``leaf_<d>.yaml`` (6 domains) + ``root_ft.yaml`` into
  ``checkpoints/gen<N>/configs/`` and returns the paths.

Seed scheme: ``seed_base`` is the two-digit generation seed family
(23 -> 231xx). ``init``-seeds differ per domain (R66 same-origin sibs:
distinct seeds, shared prior); data-seeds follow the historical
per-domain offsets. ``seed_base`` must advance on every RETRY of the
same generation (fresh-data injection, R104 stop_condition).
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

DOMAINS: list[str] = ["math", "code", "ru", "enedu", "enweb", "enwiki"]

# Per-domain overrides (measured winning-line values).
#   weights          — data mix (fresh-data lever lives here)
#   z_loss / scale   — head regularization (code is noisier: 0.003/0.3)
#   max_steps        — math saturates later (1300 vs 800)
#   lr               — H*lr band 0.35-0.38
#   tau              — math keeps inverse_sqrt_tau
#   init_off/data_off— seed offsets appended to the seed family base
_DOMAIN: dict[str, dict] = {
    "math": dict(
        weights={"openwebmath": 0.60, "edu": 0.25, "slimpajama": 0.15},
        z_loss=0.001, scale=0.4, max_steps=1300, lr=0.0005, tau=300,
        init_off=101, data_off=111,
    ),
    "code": dict(
        weights={"python_instruct": 0.60, "edu": 0.20, "slimpajama": 0.20},
        z_loss=0.003, scale=0.3, max_steps=800, lr=0.0004, tau=None,
        init_off=101, data_off=813,
    ),
    "ru": dict(
        weights={"wikipedia_ru": 0.5, "oscar_ru": 0.5},
        z_loss=0.001, scale=0.4, max_steps=800, lr=0.0005, tau=None,
        init_off=114, data_off=112,
    ),
    "enedu": dict(
        weights={"edu": 1.0},
        z_loss=0.001, scale=0.4, max_steps=800, lr=0.0005, tau=None,
        init_off=115, data_off=112,
    ),
    "enweb": dict(
        weights={"slimpajama": 1.0},
        z_loss=0.001, scale=0.4, max_steps=800, lr=0.0005, tau=None,
        init_off=116, data_off=112,
    ),
    "enwiki": dict(
        weights={"wikipedia_en": 1.0},
        z_loss=0.001, scale=0.4, max_steps=800, lr=0.0005, tau=None,
        init_off=117, data_off=112,
    ),
}

LEAF_TEMPLATE = """# Auto-generated by scripts/growth/gen_configs.py (SSOT).
# {comment} — domain `{domain}` (R66 sib-on-domain, gen {gen}).
# Do not edit by hand: change _DOMAIN in gen_configs.py.
model:
  vocab_size: 32768
  hidden_size: 128
  num_layers: 3
  loop_depth: 2
  init_seed: {init_seed}
  attention:
    num_query_heads: 2
    num_kv_heads: 1
    head_dim: 64
    rope_theta: 3000.0
    sink_len: 4
    max_seq_len: 4096
  embedding:
    tie_lm_head: false
    conv_kernel: 1
  ternary:
    enabled: false
  ffn:
    expansion: 1.0
  head:
    unigram_prior: false
    z_loss_weight: {z_loss}
    logit_scale_max: {scale}
    sampled_proposal: uniform
    fused_ce: true
  cortex:
    enabled: false
  adapters:
    enabled: true
    ttt_lora:
      enabled: true
      rank: {rank}
      alpha: 16.0
  decision:
    enabled: false
merge:
  enabled: false
  norm_block_dim: 128
  n_mixers: 1
  mixer_type: hadamard
  n_experts: 0
  expert_hidden: 0
  mixer_init_scale: 0.0
  mixer_rank: 64
  freeze_experts: false
  expert_weight_source: effective_sparse
  distill: false
train:
  init_from: {root_ckpt}
  max_steps: {max_steps}
  checkpoint_interval: 400
  checkpoint_keep_last: 3
  precision: bf16
  grad_checkpointing: false
  ternary_fp32_master: false
  batch_size: 32
  grad_accum_steps: 1
  compile_model: true
  learning_rate: {lr}
  use_muon: true
  zero_init_proj: false
  adam:
    weight_decay: 0.3
  schedule:
    warmup_steps: 200
{tau_line}  saturation_patience: 8
  saturation_tol: 0.01
  saturation_min_steps: 200
  divergence_patience: 6
  divergence_delta: 0.3
  divergence_min_steps: 150
  logging:
    log_interval: 10
    diag_interval: 100
    gate_eval_interval: 50
  checkpoint_dir: {leaf_dir}
  data:
    data_dir: data
    seq_len: 1024
    seed: {data_seed}
    weights:
{weights_block}"""

ROOT_FT_TEMPLATE = """# Auto-generated by scripts/growth/gen_configs.py (SSOT).
# Joint fine-tune of the merged root (gen {gen}).
# Do not edit by hand: change ROOT_FT_TEMPLATE in gen_configs.py.
model:
  vocab_size: 32768
  hidden_size: 128
  num_layers: 3
  loop_depth: 2
  init_seed: 15101
  attention:
    num_query_heads: 2
    num_kv_heads: 1
    head_dim: 64
    rope_theta: 3000.0
    sink_len: 4
    max_seq_len: 4096
  embedding:
    tie_lm_head: false
    conv_kernel: 1
  ternary:
    enabled: false
  ffn:
    expansion: 1.0
  head:
    unigram_prior: false
    z_loss_weight: 0.001
    logit_scale_max: 0.4
    sampled_proposal: uniform
    fused_ce: true
  cortex:
    enabled: false
  adapters:
    enabled: true
    ttt_lora:
      enabled: true
      rank: {rank}
      alpha: 16.0
  decision:
    enabled: false
merge:
  enabled: false
  norm_block_dim: 128
  n_mixers: 1
  mixer_type: hadamard
  n_experts: 0
  expert_hidden: 0
  mixer_init_scale: 0.0
  mixer_rank: 64
  freeze_experts: false
  expert_weight_source: effective_sparse
  distill: false
train:
  init_from: {root_ckpt}
  max_steps: 600
  checkpoint_interval: 400
  checkpoint_keep_last: 3
  precision: bf16
  grad_checkpointing: false
  ternary_fp32_master: false
  batch_size: 32
  grad_accum_steps: 1
  compile_model: true
  # lr band H*lr 0.35-0.38
  learning_rate: 0.0002
  use_muon: true
  zero_init_proj: false
  adam:
    weight_decay: 0.3
  schedule:
    warmup_steps: 200
    inverse_sqrt_tau: 300
  saturation_patience: 8
  saturation_tol: 0.01
  saturation_min_steps: 200
  divergence_patience: 6
  divergence_delta: 0.3
  divergence_min_steps: 150
  logging:
    log_interval: 10
    diag_interval: 100
    gate_eval_interval: 50
  checkpoint_dir: {ft_dir}
  data:
    data_dir: data
    seq_len: 1024
    seed: {data_seed}
    weights:
{weights_block}"""


def _weights_block(weights: dict[str, float]) -> str:
    return "\n".join(f"      {k}: {v}" for k, v in weights.items())


def write_generation(
    gen: int,
    root_ckpt: str,
    seed_base: int,
    rank: int = 64,
    domains: list[str] | None = None,
    out_dir: Path | None = None,
) -> dict[str, Path]:
    """Materialize gen-N configs under ``checkpoints/gen<N>/configs/``.

    ``seed_base``: the seed family (e.g. 23 -> seeds 231xx). Advance it
    (24, 25, ...) on every retry of the same generation.
    """
    domains = domains or DOMAINS
    out = out_dir or (ROOT / f"checkpoints/gen{gen}/configs")
    out.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for d in domains:
        c = _DOMAIN[d]
        tau_line = (
            f"    inverse_sqrt_tau: {c['tau']}\n" if c["tau"] else ""
        )
        s = LEAF_TEMPLATE.format(
            comment="Latent-line leaf", domain=d, gen=gen,
            init_seed=seed_base * 1000 + c["init_off"],
            z_loss=c["z_loss"], scale=c["scale"], rank=rank,
            root_ckpt=root_ckpt, max_steps=c["max_steps"], lr=c["lr"],
            tau_line=tau_line,
            leaf_dir=f"checkpoints/gen{gen}_leaf_{d}",
            data_seed=seed_base * 1000 + c["data_off"],
            weights_block=_weights_block(c["weights"]),
        )
        p = out / f"leaf_{d}.yaml"
        p.write_text(s, encoding="utf-8")
        paths[f"leaf_{d}"] = p
    # root_ft: the ladder's ACTUAL historical mix (Map≠Territory: taken
    # from the derive-chain, not from mix.json).
    root_mix = {
        "edu": 0.2, "slimpajama": 0.15, "openwebmath": 0.25,
        "oscar_ru": 0.1, "wikipedia_ru": 0.1, "python_instruct": 0.2,
    }
    s = ROOT_FT_TEMPLATE.format(
        gen=gen, rank=rank,
        root_ckpt=f"checkpoints/gen{gen}_root/root.pt",
        ft_dir=f"checkpoints/gen{gen}_root_ft",
        data_seed=15111,  # pinned: the ladder's common eval/train seed
        weights_block=_weights_block(root_mix),
    )
    p = out / "root_ft.yaml"
    p.write_text(s, encoding="utf-8")
    paths["root_ft"] = p
    return paths


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--gen", type=int, required=True)
    ap.add_argument("--root", required=True, help="incumbent root checkpoint")
    ap.add_argument("--seed-base", type=int, required=True,
                    help="seed family, e.g. 24 -> seeds 241xx")
    ap.add_argument("--rank", type=int, default=64)
    args = ap.parse_args()
    for name, p in write_generation(args.gen, args.root, args.seed_base,
                                    args.rank).items():
        print(f"{name}: {p}")
