"""Generate the flat-merge control for the F3 tree-vs-flat experiment.

Why this exists: the pre-registered claim in STATUS.md is

    at equal parameters, an F3 tree with root cortex beats a flat merge.

Both arms must therefore carry the SAME parameter count and the SAME joint
budget, or the comparison proves nothing (this is exactly the confound that
took three controls to close for N=6 in STATUS.md point 4). The tree parent
is hidden 1152 = 3 x 384, so the flat control is the same three leaves joined
by the ordinary block-diagonal path with the same head geometry. The only
difference between the arms is the lift: `parent_preserving` F3 tree versus
the plain concatenation.

Both ffn expansions are pinned to 1.0 because that is how the leaves were
actually trained; the 8/3 default builds a 1024-wide leaf mixer and the
merge then fails on a shape mismatch (see .omc/attempts/f3_tree_vs_flat).

Usage:
    python scripts/make_flat_control.py
    python scripts/make_flat_control.py --expansion 1.0
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from hagi.config import load_config  # noqa: E402

LEAF_SEEDS = (1001, 1002, 1003)
ROOT = Path(__file__).resolve().parents[1]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--expansion", type=float, default=1.0)
    ap.add_argument("--steps", type=int, default=9000)
    args = ap.parse_args()

    # Derive from the real parent config rather than restating the geometry:
    # the control must match the tree arm in every field the tree arm fixes.
    parent = load_config(ROOT / "configs/f3_parent_d1.yaml")
    model = parent.model
    out = {
        "model": {
            "vocab_size": model.vocab_size,
            "hidden_size": model.hidden_size,
            "num_layers": model.num_layers,
            "loop_depth": model.loop_depth,
            "init_seed": model.init_seed,
            "attention": {
                "num_query_heads": model.attention.num_query_heads,
                "num_kv_heads": model.attention.num_kv_heads,
                "head_dim": model.attention.head_dim,
                "max_seq_len": model.attention.max_seq_len,
            },
            "embedding": {
                "tie_lm_head": model.embedding.tie_lm_head,
                "conv_kernel": model.embedding.conv_kernel,
            },
            "ternary": {"enabled": False},
            "ffn": {"expansion": args.expansion},
            "head": {
                "unigram_prior": False,
                "sampled_proposal": "uniform",
            },
            "cortex": {"enabled": False},
            "adapters": {"enabled": False},
            "decision": {"enabled": False},
        },
        "merge": {
            "enabled": True,
            "mixer_type": "hadamard",
            "n_experts": 3,
            "expert_hidden": model.hidden_size // 3,
            "mixer_init_scale": 0.0,
            "mixer_rank": 64,
            "freeze_experts": False,
            "expert_checkpoints": [
                f"checkpoints/f3_leaf_s{s}/step-0003000.pt" for s in LEAF_SEEDS
            ],
        },
        "train": {
            "max_steps": args.steps,
            "checkpoint_interval": 1000,
            "precision": "bf16",
            "ternary_fp32_master": False,
            "batch_size": parent.train.batch_size,
            "grad_accum_steps": parent.train.grad_accum_steps,
            "learning_rate": parent.train.learning_rate,
            "checkpoint_dir": "checkpoints/flat3_d1",
            "data": {
                "data_dir": parent.train.data.data_dir,
                "seq_len": parent.train.data.seq_len,
                "seed": parent.train.data.seed,
                "weights": dict(parent.train.data.weights),
            },
        },
    }

    dest = ROOT / "configs/f3_flat_d1.yaml"
    header = (
        "# GENERATED by scripts/make_flat_control.py -- do not hand-edit.\n"
        "# Flat block-diagonal control for the F3 tree-vs-flat experiment.\n"
        f"# Loads clean: python -c \"import sys;sys.path.insert(0,'src');"
        f"from hagi.config import load_config;load_config('{dest.as_posix()}')\"\n"
    )
    import yaml

    dest.write_text(header + yaml.safe_dump(out, sort_keys=False), encoding="utf-8")

    # Fail closed: a control that does not load is not a control.
    cfg = load_config(dest)
    print(f"wrote {dest}")
    print(f"  hidden={cfg.model.hidden_size} experts={cfg.merge.n_experts} "
          f"x{cfg.merge.expert_hidden} mixer={cfg.merge.mixer_type} "
          f"cortex={cfg.model.cortex.enabled}")
    from hagi.config import ffn_width

    print(f"  ffn_width={ffn_width(cfg.model)} (must equal 3x the leaf width)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
